name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version-file: '.ruby-version'
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3

    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Compile assets
      run: |
        bundle exec rails assets:precompile

    - name: Run RSpec tests
      run: |
        bundle exec rspec --format documentation
